[package]
name = "rs-lib"
version = "0.1.0"
authors = ["Andrew Thauer"]
edition = "2018"
description = "Rust library for WASM example"

[lib]
crate-type = ["cdylib"]

[dependencies]
wasm-bindgen = "0.2"
wasm-bindgen-test = "0.2"

[build-dependencies]
cargo-make = "0.19"
